/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;
import Controller.AdminController;
import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.awt.Color;
/**
 *
 * @author Aqil Anhein
 */
public class AdminMainMenu extends javax.swing.JFrame {
private final AdminController adminController;
    /**
     * Creates new form AdminMainMenu
     */
    public AdminMainMenu() {
        initComponents();
        Color col = new Color(248,247,243);
        getContentPane().setBackground(col);
        this.adminController = new AdminController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddWagonDialog = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        ButtonWagonKereta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ButtonWagonBaru = new javax.swing.JButton();
        BackButtonAddWagon = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        AddRouteDialog = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        FromField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DestinationField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        DurationSpinner = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        RouteCancel = new javax.swing.JButton();
        SaveRouteButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        RouteNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        AddWagonButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        AddRouteButton = new javax.swing.JButton();
        AddTrainButton = new javax.swing.JButton();

        jLabel2.setText("Tambahkan wagon ke kereta");

        ButtonWagonKereta.setText("Klik Sini");
        ButtonWagonKereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonWagonKeretaActionPerformed(evt);
            }
        });

        jLabel3.setText("Buat Wagon baru");

        ButtonWagonBaru.setText("klik Sini");
        ButtonWagonBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonWagonBaruActionPerformed(evt);
            }
        });

        BackButtonAddWagon.setText("Back");
        BackButtonAddWagon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonAddWagonActionPerformed(evt);
            }
        });

        jLabel4.setText(" yang sudah ada");

        javax.swing.GroupLayout AddWagonDialogLayout = new javax.swing.GroupLayout(AddWagonDialog.getContentPane());
        AddWagonDialog.getContentPane().setLayout(AddWagonDialogLayout);
        AddWagonDialogLayout.setHorizontalGroup(
            AddWagonDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddWagonDialogLayout.createSequentialGroup()
                .addGroup(AddWagonDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddWagonDialogLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(AddWagonDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(AddWagonDialogLayout.createSequentialGroup()
                                .addGroup(AddWagonDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonWagonBaru))
                            .addGroup(AddWagonDialogLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonWagonKereta))))
                    .addGroup(AddWagonDialogLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(BackButtonAddWagon, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        AddWagonDialogLayout.setVerticalGroup(
            AddWagonDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddWagonDialogLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(AddWagonDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddWagonDialogLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(ButtonWagonKereta))
                .addGap(25, 25, 25)
                .addGroup(AddWagonDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(ButtonWagonBaru))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(BackButtonAddWagon)
                .addGap(62, 62, 62))
        );

        jLabel5.setText("Add New Route");

        jLabel6.setText("From");

        jLabel7.setText("Destination");

        jLabel8.setText("Duration");

        jLabel9.setText("Minutes");

        RouteCancel.setText("Cancel");
        RouteCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RouteCancelActionPerformed(evt);
            }
        });

        SaveRouteButton.setText("Save");
        SaveRouteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveRouteButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Route Name");

        javax.swing.GroupLayout AddRouteDialogLayout = new javax.swing.GroupLayout(AddRouteDialog.getContentPane());
        AddRouteDialog.getContentPane().setLayout(AddRouteDialogLayout);
        AddRouteDialogLayout.setHorizontalGroup(
            AddRouteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddRouteDialogLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(RouteCancel)
                .addGap(28, 28, 28))
            .addGroup(AddRouteDialogLayout.createSequentialGroup()
                .addGroup(AddRouteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddRouteDialogLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(AddRouteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(44, 44, 44)
                        .addGroup(AddRouteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FromField)
                            .addComponent(DestinationField)
                            .addGroup(AddRouteDialogLayout.createSequentialGroup()
                                .addComponent(DurationSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9))
                            .addComponent(RouteNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                    .addGroup(AddRouteDialogLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(SaveRouteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddRouteDialogLayout.setVerticalGroup(
            AddRouteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddRouteDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddRouteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(RouteCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(AddRouteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(RouteNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddRouteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FromField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(AddRouteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(DestinationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(AddRouteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(DurationSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(30, 30, 30)
                .addComponent(SaveRouteButton)
                .addGap(46, 46, 46))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Admin Main Menu");

        AddWagonButton.setText("Add Wagon");
        AddWagonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddWagonButtonActionPerformed(evt);
            }
        });

        LogOutButton.setText("Log Out");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        AddRouteButton.setText("Add Route");
        AddRouteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRouteButtonActionPerformed(evt);
            }
        });

        AddTrainButton.setText("Add Train");
        AddTrainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTrainButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LogOutButton)
                .addGap(158, 158, 158))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddRouteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddTrainButton, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(AddWagonButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(116, 116, 116))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(AddWagonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddRouteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddTrainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(LogOutButton)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showAddWagonDialog() {
        AddWagonDialog.setSize(500, 350);
        AddWagonDialog.setVisible(true);
    }
    
    public void showAddRouteDialog() {
        AddRouteDialog.setSize(500, 350);
        AddRouteDialog.setVisible(true);
    }
    private void AddWagonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddWagonButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        showAddWagonDialog();
               
    }//GEN-LAST:event_AddWagonButtonActionPerformed

    private void BackButtonAddWagonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonAddWagonActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        AddWagonDialog.setVisible(false);
    }//GEN-LAST:event_BackButtonAddWagonActionPerformed

    private void ButtonWagonBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonWagonBaruActionPerformed
        // TODO add your handling code here
        AddWagonForm wagonform = new AddWagonForm();
        AddWagonDialog.setVisible(false);
        wagonform.setVisible(true);
    }//GEN-LAST:event_ButtonWagonBaruActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            this.dispose();
        
            // Open the login frame
            LoginFrame loginFrame = new LoginFrame();
            loginFrame.setVisible(true);
            
        }
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void RouteCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RouteCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        AddRouteDialog.setVisible(false);
    }//GEN-LAST:event_RouteCancelActionPerformed

    private void AddRouteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRouteButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        showAddRouteDialog();
        RouteNameField.setText("");
        FromField.setText("");
        DestinationField.setText("");
        DurationSpinner.setValue(0);
    }//GEN-LAST:event_AddRouteButtonActionPerformed

    private void SaveRouteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveRouteButtonActionPerformed
        // TODO add your handling code here:
        String name = RouteNameField.getText();
        String from = FromField.getText();
        String dest = DestinationField.getText();
        Integer dur = (int)DurationSpinner.getValue();
        if (adminController.addNewRoute(name, from, dest, dur)){
            
            JOptionPane.showMessageDialog(this, "New Route Added Successfully");
            // Handle successful login
            
            AddRouteDialog.setVisible(false);
            this.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(this, "Insertion Unsuccessful");
        
        }
    }//GEN-LAST:event_SaveRouteButtonActionPerformed

    private void AddTrainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTrainButtonActionPerformed
        // TODO add your handling code here:
        AddTrainForm trainform = new AddTrainForm();
        this.setVisible(false);
        trainform.setVisible(true);
        
    }//GEN-LAST:event_AddTrainButtonActionPerformed

    private void ButtonWagonKeretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonWagonKeretaActionPerformed
        // TODO add your handling code here:
        AddWagonToTrainForm form = new AddWagonToTrainForm();
        AddWagonDialog.setVisible(false);
        form.setVisible(true);
    }//GEN-LAST:event_ButtonWagonKeretaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRouteButton;
    private javax.swing.JDialog AddRouteDialog;
    private javax.swing.JButton AddTrainButton;
    private javax.swing.JButton AddWagonButton;
    private javax.swing.JDialog AddWagonDialog;
    private javax.swing.JButton BackButtonAddWagon;
    private javax.swing.JButton ButtonWagonBaru;
    private javax.swing.JButton ButtonWagonKereta;
    private javax.swing.JTextField DestinationField;
    private javax.swing.JSpinner DurationSpinner;
    private javax.swing.JTextField FromField;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton RouteCancel;
    private javax.swing.JTextField RouteNameField;
    private javax.swing.JButton SaveRouteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
