/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JOptionPane;
import Controller.MainMenuController;
/**
 *
 * @author Aqil Anhein
 */
public class UserMainMenu extends javax.swing.JFrame {
    private final MainMenuController mmcontroller;
    /**
     * Creates new form UserMainMenu
     */
    public UserMainMenu() {
        initComponents();
        Color col = new Color(248,247,243);
        getContentPane().setBackground(col);
        this.mmcontroller = new MainMenuController();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReviewDialog = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReviewHistoryTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ReviewBackButton = new javax.swing.JButton();
        EditProfileButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        BookButton = new javax.swing.JButton();
        ViewBookingsButton = new javax.swing.JButton();
        BookingHistoryButton = new javax.swing.JButton();
        ReviewHistoryButton = new javax.swing.JButton();

        ReviewHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ReviewHistoryTable);

        jLabel1.setText("Reviews");

        ReviewBackButton.setText("Back");
        ReviewBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReviewDialogLayout = new javax.swing.GroupLayout(ReviewDialog.getContentPane());
        ReviewDialog.getContentPane().setLayout(ReviewDialogLayout);
        ReviewDialogLayout.setHorizontalGroup(
            ReviewDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReviewDialogLayout.createSequentialGroup()
                .addGroup(ReviewDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReviewDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ReviewDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(ReviewDialogLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(ReviewBackButton)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        ReviewDialogLayout.setVerticalGroup(
            ReviewDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReviewDialogLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(ReviewBackButton)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EditProfileButton.setText("Edit Profile");
        EditProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileButtonActionPerformed(evt);
            }
        });

        LogOutButton.setText("Log Out");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        BookButton.setText("Book a Train");
        BookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookButtonActionPerformed(evt);
            }
        });

        ViewBookingsButton.setText("View Bookings");
        ViewBookingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBookingsButtonActionPerformed(evt);
            }
        });

        BookingHistoryButton.setText("View Booking History");
        BookingHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingHistoryButtonActionPerformed(evt);
            }
        });

        ReviewHistoryButton.setText("View User Reviews");
        ReviewHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewHistoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EditProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(BookButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ViewBookingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BookingHistoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(LogOutButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(ReviewHistoryButton)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditProfileButton)
                    .addComponent(ViewBookingsButton))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookButton)
                    .addComponent(BookingHistoryButton))
                .addGap(45, 45, 45)
                .addComponent(ReviewHistoryButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(LogOutButton)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileButtonActionPerformed
        // TODO add your handling code here:
        EditProfileForm editprofileform = new EditProfileForm();
        editprofileform.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EditProfileButtonActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            this.dispose();
        
            // Open the login frame
            LoginFrame loginFrame = new LoginFrame();
            loginFrame.setVisible(true);
            
        }
        
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void BookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        BookATrainForm form = new BookATrainForm();
        form.setVisible(true);
                
    }//GEN-LAST:event_BookButtonActionPerformed

    private void ViewBookingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBookingsButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewBookingsForm form = new ViewBookingsForm();
        form.setVisible(true);
    }//GEN-LAST:event_ViewBookingsButtonActionPerformed

    private void BookingHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingHistoryButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        BookingHistoryForm form = new BookingHistoryForm();
        form.setVisible(true);
    }//GEN-LAST:event_BookingHistoryButtonActionPerformed

    private void ReviewHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewHistoryButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ReviewDialog.setSize(600,350);
        ReviewDialog.setVisible(true);
        mmcontroller.showReviewHistoryForUser(ReviewHistoryTable);
        
    }//GEN-LAST:event_ReviewHistoryButtonActionPerformed

    private void ReviewBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewBackButtonActionPerformed
        // TODO add your handling code here:
        ReviewDialog.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_ReviewBackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookButton;
    private javax.swing.JButton BookingHistoryButton;
    private javax.swing.JButton EditProfileButton;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton ReviewBackButton;
    private javax.swing.JDialog ReviewDialog;
    private javax.swing.JButton ReviewHistoryButton;
    private javax.swing.JTable ReviewHistoryTable;
    private javax.swing.JButton ViewBookingsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
